In [1]:
from scr.utils import read_CLINC150_file, get_label_set, turn_single_label_to_multilabels

dataDict = read_CLINC150_file('data/CLINC150/data_full.json')
trainList = dataDict['train']
valList = dataDict['val']
testList = dataDict['test']
labelSet = get_label_set(trainList, valList, testList)

turn_single_label_to_multilabels(trainList, testList, valList)

d:\Projects\BertClassifier\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


The keys found in this json are:  dict_keys(['oos_val', 'val', 'train', 'oos_test', 'test', 'oos_train'])


In [2]:
from scr.dataset import SentenceLabelDataset

trainSet = SentenceLabelDataset(trainList, labelSet)

In [3]:
from torch.utils.data import DataLoader
from scr.dataset import collate_dynamic_padding

dataloader = DataLoader(trainSet, 
                        batch_size = 8, 
                        num_workers = 2, 
                        shuffle = True,
                        collate_fn = collate_dynamic_padding,
                        pin_memory = True)

In [7]:
from scr.evaluate import MultiLabelEvaluator
import torch


FUNCTION_MAP = {'accuracy' : MultiLabelEvaluator.get_accuracy,
                'precision' : MultiLabelEvaluator.get_precision,
                'recall' : MultiLabelEvaluator.get_recall,
                'f1' : MultiLabelEvaluator.get_F1}

filter = ['Accuracy']

targets = [[1,0,1], [1,0,0], [1,1,0],[1,1,1]]
preds = [[1,0,0], [0,1,0], [1,1,0], [1,0,0]]
targets = torch.as_tensor(targets)
preds = torch.as_tensor(preds)


funs = [FUNCTION_MAP[fil.lower()] for fil in filter]
evaluator = MultiLabelEvaluator()
evaluator.add_batch(probs = preds, targets=targets)
for fun in funs:
    print(fun(evaluator))


(tensor([0.7500, 0.3333, 0.0000]), 0.4444444477558136)


In [4]:
from torch.nn import Sigmoid
import torch

temp = [[15,2,-1],[1,4,6]]
temp = torch.as_tensor(temp)

sigmoid = Sigmoid()
print(sigmoid(temp))

tensor([[1.0000, 0.8808, 0.2689],
        [0.7311, 0.9820, 0.9975]])


In [3]:
evaluator.truePositive

tensor([[1, 0, 0],
        [0, 0, 0],
        [1, 1, 0],
        [1, 1, 0]], dtype=torch.int32)

In [5]:
'Accuracy'.lower()

'accuracy'

In [11]:
torch.where(evaluator.truePositive==0, preds, 0)

tensor([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
evaluator.positive

tensor([[1, 0, 1],
        [1, 1, 0],
        [1, 1, 0],
        [1, 1, 1]], dtype=torch.int32)

In [46]:
print(preds)
print(preds[:,2])


tensor([[1, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]], dtype=torch.int32)
tensor([0, 1, 1, 1], dtype=torch.int32)
